public class EjecutarCola{
    public static void main(String[] args){

            Queue<Integer> numeros = new ArrayDeque<>();

            numeros.add(e:1);
            numeros.add(e:2);
            numeros.add(e:3);
            numeros.add(e:4);
            numeros.add(e:5);
            numeros.add(e:6);
            numeros.add(e:7);


            // Mostrar la cola
            System.out.println(nombres);//[1,2,3,4,5,6,7]
        
            //Mostrare el primer elemento de la colo
            System.out.println(nombres.element()); //1


            
            //Agraga un elemento a la cola
            numeros.offer(8);
            
            System.out.println(nombres);//[1,2,3,4,5,6,7]
            //Remueve la cabeza de la cola
            System.out.println(nombres.peek());

    }
}